/**
 * Port of OpenAI.gs makeMockAiResult_.
 * Active when BETA_MOCK_MODE === "true". No network call, no API spend.
 */
import type { PitchDeskOutput, GenerateInput } from "./schema";
import { getFirstName } from "@/lib/utils";

export function makeMockResult(input: GenerateInput): PitchDeskOutput {
  const company = input.company;
  const contact = input.contact;
  const controls = input.controls;
  const firstName = getFirstName(contact.contact_name);
  const companyName = company.company_name || "your company";
  const pitchType = controls.pitch_type || "General Employer";
  const subPitch = controls.sub_pitch || "AI choose best";
  const product = controls.product_offer || "AI choose best";

  const shortEmail = [
    `Hi ${firstName},`,
    "",
    `I wanted to put O1DMatch on your radar for ${companyName}.`,
    "",
    "We help employers access accomplished international talent without asking the employer to run a traditional H-1B sponsorship process. When there is a candidate you would consider engaging if work-authorized, the employer role can be as simple as a one-page interest letter.",
    "",
    "The candidate's case is filed through an authorized agent or petitioner. Your company does not file, you are not the visa petitioner, and you do not pay the USCIS filing fee.",
    "",
    "Would it be worth a short conversation to see whether this could support your hiring needs?",
    "",
    "The legal read belongs to your attorney. The employer and itinerary problem belongs to O1DMatch.",
  ].join("\n");

  const personalizedEmail = [
    `Hi ${firstName},`,
    "",
    `I came across ${companyName} and wanted to reach out directly. Based on what we have seen of ${company.industry || "your industry"}, there may be a practical angle worth a short conversation.`,
    "",
    "O1DMatch is an AI-powered software platform and two-sided marketplace that connects O-1-ready international talent with US employers. The employer side of the workflow can be as light as a one-page interest letter for candidates you would consider engaging if work-authorized.",
    "",
    "The candidate's case is filed through an authorized agent or petitioner. Your company does not file. You are not the visa petitioner. You do not pay the USCIS filing fee. You are not running an H-1B sponsorship process.",
    "",
    "If this is interesting we can set up a 20-minute call to walk through how it fits your team's hiring approach.",
    "",
    "The legal read belongs to your attorney. The employer and itinerary problem belongs to O1DMatch.",
  ].join("\n");

  return {
    employer_analysis: {
      company_summary: `${companyName} appears to be a potential fit based on the pasted research.`,
      contact_summary: `${contact.contact_name || "This contact"} is being approached as ${contact.contact_type || "Unknown"}.`,
      employer_type: pitchType,
      contact_type: contact.contact_type || "Unknown",
      selected_pitch_type: pitchType,
      selected_sub_pitch: subPitch,
      selected_product_offer: product,
      fit_score: 7,
      urgency_score: 6,
      why_this_pitch:
        "Mock mode is on. This draft uses the selected pitch and contact type but does not call the live model.",
      likely_objections: ["We do not sponsor visas.", "The process sounds complicated."],
    },
    drafts: {
      subject_lines: [`Quick idea for ${companyName}`, "International talent question"],
      short_email: shortEmail,
      personalized_email: personalizedEmail,
      follow_up_email: `Hi ${firstName}, just bringing this back up. Is there someone on your team who reviews alternative international hiring paths, or would feedback from your side be useful?`,
      call_notes:
        "Open with the business problem. Explain that the employer is not filing and that the one-page interest letter is the first practical step.",
      crm_notes: "Mock draft generated. Review company details before use.",
      objection_responses: [
        {
          objection: "We do not sponsor visas.",
          response:
            "That is exactly the point. The candidate's case is filed through an authorized agent or petitioner. Your company does not file.",
        },
        {
          objection: "This sounds complicated.",
          response:
            "The initial employer role can be a one-page interest letter confirming potential interest if the candidate is work-authorized.",
        },
      ],
    },
    quality_control: {
      legal_language_check: "Mock result uses safe language.",
      brand_check: "Plain text and strict O1DMatch brand.",
      missing_information: [],
      copy_warnings: ["BETA_MOCK_MODE is true. This was not generated by the live model."],
    },
  };
}
